var quotes = [
  /*1*/ "What you think, you become. What you feel, you attract. What you imagine, you create.",
  /*2*/ "The successful warrior is the average man, with laser-like focus.",
  /*3*/ "Happiness depends upon ourselves.",
  /*4*/ "Life is either a daring adventure or nothing at all.",
  /*5*/ "Do what you can with what you have where you are.",
  /*6*/ "Don’t wait. The time will never be just right.",
  /*7*/ "Only those who dare to fail greatly can ever achieve greatly.",
  /*8*/ "The more you praise and celebrate your life, the more there is in life to celebrate.",
  /*9*/ "Success is the sum of small efforts, repeated day in and day out.",
  /*10*/ "Don’t be afraid to give up the good to go for the great.",
  /*11*/ "Do not let what you cannot do interfere with what you can do.",
  /*12*/ "The only way to achieve the impossible is to believe it is possible.",
  /*13*/ "To handle yourself, use your head; to handle others, use your heart.",
  /*14*/ "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  /*15*/ "Success is not measured by the position one has reached in life, rather by the obstacles one overcomes while trying to succeed.",
  /*16*/ "Don’t let the noise of others’ opinions drown out your own inner voice.",
  /*17*/ "Do one thing every day that scares you.",
  /*18*/ "Hardships often prepare ordinary people for an extraordinary destiny.",
  /*19*/ "It does not matter how slowly you go as long as you do not stop.",
  /*20*/ "Our greatest glory is not in never falling, but in rising every time we fall.",
  /*21*/ "What we think, we become.",
  /*22*/ "The future depends on what you do today.",
  /*23*/ "Don’t count the days, make the days count.",
  /*24*/ "Success is getting what you want. Happiness is wanting what you get.",
  /*25*/ "Action is the foundational key to all success.",
  /*26*/ "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
  /*27*/ "Courage is grace under pressure.",
  /*28*/ "Success is not how high you have climbed, but how you make a positive difference to the world.",
  /*29*/ "Life is made of ever so many partings welded together.",
  /*30*/ "Turn your wounds into wisdom.",
  /*31*/ "In order to write about life, first you must live it.",
  /*32*/ "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
  /*33*/ "Life is short, and it’s up to you to make it sweet.",
  /*34*/ "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  /*35*/ "The biggest risk is not taking any risk.",
  /*36*/ "It always seems impossible until it’s done.",
  /*37*/ "Success isn’t overnight. It’s when every day you get a little better than the day before. It all adds up.",
  /*38*/ "Don’t wish it were easier. Wish you were better.",
  /*39*/ "The road to success and the road to failure are almost exactly the same.",
  /*40*/ "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
  /*41*/ "Keep smiling, because life is a beautiful thing and there’s so much to smile about.",
  /*42*/ "Happiness is not something you postpone for the future; it is something you design for the present.",
  /*43*/ "The best way out is always through.",
  /*44*/ "Life isn’t about finding yourself. It’s about creating yourself.",
  /*45*/ "The difference between ordinary and extraordinary is that little extra.",
  /*46*/ "Do what you feel in your heart to be right – for you’ll be criticized anyway.",
  /*47*/ "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
  /*48*/ "Opportunities are usually disguised as hard work, so most people don’t recognize them.",
  /*49*/ "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  /*50*/ "It’s not the years in your life that count. It’s the life in your years.",
  /*1*/ "Success is liking yourself, liking what you do, and liking how you do it.",
  /*2*/ "Happiness is not something ready-made. It comes from your own actions.",
  /*3*/ "Be the change that you wish to see in the world.",
  /*4*/ "Keep going. Everything you need will come to you at the perfect time.",
  /*5*/ "Don’t wait. The time will never be just right.",
  /*6*/ "Do what you can with all you have, wherever you are.",
  /*7*/ "You must expect great things of yourself before you can do them.",
  /*8*/ "With the new day comes new strength and new thoughts.",
  /*9*/ "Start where you are. Use what you have. Do what you can.",
  /*10*/ "It always seems impossible until it’s done.",
  /*11*/ "Don’t let the fear of striking out hold you back.",
  /*12*/ "The way to get started is to quit talking and begin doing.",
  /*13*/ "The secret of success is to do the common thing uncommonly well.",
  /*14*/ "The difference between who you are and who you want to be is what you do.",
  /*15*/ "Success doesn’t come to you. You go to it.",
  /*16*/ "Motivation is what gets you started. Habit is what keeps you going.",
  /*17*/ "The best revenge is massive success.",
  /*18*/ "Success is not in what you have, but who you are.",
  /*19*/ "Don’t let yesterday take up too much of today.",
  /*20*/ "Opportunities don’t happen. You create them.",
  /*21*/ "Your big opportunity may be right where you are now.",
  /*22*/ "You are braver than you believe, stronger than you seem, and smarter than you think.",
  /*23*/ "No matter how hard the past, you can always begin again.",
  /*24*/ "Success usually comes to those who are too busy to be looking for it.",
  /*25*/ "All progress takes place outside the comfort zone.",
  /*26*/ "Do not be embarrassed by your failures, learn from them and start again.",
  /*27*/ "Ambition is the path to success. Persistence is the vehicle you arrive in.",
  /*28*/ "I never dreamed about success, I worked for it.",
  /*29*/ "Success isn’t about how much money you make; it’s about the difference you make in people’s lives.",
  /*30*/ "The harder you work for something, the greater you’ll feel when you achieve it.",
  /*31*/ "The only limit to our realization of tomorrow will be our doubts of today.",
  /*32*/ "You don’t have to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.",
  /*33*/ "Happiness lies in the joy of achievement and the thrill of creative effort.",
  /*34*/ "Courage is resistance to fear, mastery of fear, not absence of fear.",
  /*35*/ "It’s not whether you get knocked down; it’s whether you get up.",
  /*36*/ "You must do the things you think you cannot do.",
  /*37*/ "To succeed in life, you need two things: ignorance and confidence.",
  /*38*/ "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  /*39*/ "A champion is defined not by their wins but by how they can recover when they fall.",
  /*40*/ "The man who moves a mountain begins by carrying away small stones.",
  /*41*/ "Fall seven times and stand up eight.",
  /*42*/ "Your time is limited, don’t waste it living someone else’s life.",
  /*43*/ "Believe you can and you’re halfway there.",
  /*44*/ "Life is really simple, but we insist on making it complicated.",
  /*45*/ "Keep your face always toward the sunshine—and shadows will fall behind you.",
  /*46*/ "Opportunities multiply as they are seized.",
  /*47*/ "What would life be if we had no courage to attempt anything?",
  /*48*/ "Life is what happens when you’re busy making other plans.",
  /*49*/ "A person who never made a mistake never tried anything new.",
  /*50*/ "Act as if what you do makes a difference. It does.",
  /*1*/ "Don’t watch the clock; do what it does. Keep going.",
  /*2*/ "A goal is a dream with a deadline.",
  /*3*/ "The only place where success comes before work is in the dictionary.",
  /*4*/ "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
  /*5*/ "Perseverance is not a long race; it is many short races one after the other.",
  /*6*/ "Setting goals is the first step in turning the invisible into the visible.",
  /*7*/ "Quality is not an act, it is a habit.",
  /*8*/ "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  /*9*/ "Success usually comes to those who are too busy to be looking for it.",
  /*10*/ "Try not to become a person of success, but rather try to become a person of value.",
  /*11*/ "The harder the conflict, the greater the triumph.",
  /*12*/ "Opportunities don’t happen. You create them.",
  /*13*/ "Don’t be afraid to give up the good to go for the great.",
  /*14*/ "Success is not in what you have, but who you are.",
  /*15*/ "Act as if what you do makes a difference. It does.",
  /*16*/ "Fall seven times and stand up eight.",
  /*17*/ "Do what you feel in your heart to be right – for you’ll be criticized anyway.",
  /*18*/ "Limit your 'always' and your 'nevers'.",
  /*19*/ "Nothing is impossible. The word itself says 'I’m possible!'",
  /*20*/ "What we achieve inwardly will change outer reality.",
  /*21*/ "Don’t count the days, make the days count.",
  /*22*/ "We become what we think about.",
  /*23*/ "Do one thing every day that scares you.",
  /*24*/ "Life is what we make it, always has been, always will be.",
  /*25*/ "The best way out is always through.",
  /*26*/ "We may encounter many defeats but we must not be defeated.",
  /*27*/ "Life isn’t about finding yourself. It’s about creating yourself.",
  /*28*/ "Success is how high you bounce when you hit bottom.",
  /*29*/ "The question isn’t who is going to let me; it’s who is going to stop me.",
  /*30*/ "Everything you’ve ever wanted is on the other side of fear.",
  /*31*/ "Be yourself; everyone else is already taken.",
  /*32*/ "Do not let what you cannot do interfere with what you can do.",
  /*33*/ "Do something wonderful, people may imitate it.",
  /*34*/ "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  /*35*/ "Success is getting what you want. Happiness is wanting what you get.",
  /*36*/ "Be a positive energy trampoline – absorb what you need and rebound more back.",
  /*37*/ "When we strive to become better than we are, everything around us becomes better too.",
  /*38*/ "I never lose. Either I win or I learn.",
  /*39*/ "You don’t need to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.",
  /*40*/ "Hardships often prepare ordinary people for an extraordinary destiny.",
  /*41*/ "The best preparation for tomorrow is doing your best today.",
  /*42*/ "Courage is resistance to fear, mastery of fear—not absence of fear.",
  /*43*/ "Success is not how high you have climbed, but how you make a positive difference to the world.",
  /*44*/ "Turn your wounds into wisdom.",
  /*45*/ "Keep your face always toward the sunshine—and shadows will fall behind you.",
  /*46*/ "In a gentle way, you can shake the world.",
  /*47*/ "If you’re going through hell, keep going.",
  /*48*/ "Start where you are. Use what you have. Do what you can.",
  /*49*/ "The best time to plant a tree was 20 years ago. The second best time is now.",
  /*50*/ "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.",
  /*1*/ "Don’t watch the clock; do what it does. Keep going.",
  /*2*/ "A goal is a dream with a deadline.",
  /*3*/ "The only place where success comes before work is in the dictionary.",
  /*4*/ "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.",
  /*5*/ "Perseverance is not a long race; it is many short races one after the other.",
  /*6*/ "Setting goals is the first step in turning the invisible into the visible.",
  /*7*/ "Quality is not an act, it is a habit.",
  /*8*/ "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  /*9*/ "Success usually comes to those who are too busy to be looking for it.",
  /*10*/ "Try not to become a person of success, but rather try to become a person of value.",
  /*11*/ "The harder the conflict, the greater the triumph.",
  /*12*/ "Opportunities don’t happen. You create them.",
  /*13*/ "Don’t be afraid to give up the good to go for the great.",
  /*14*/ "Success is not in what you have, but who you are.",
  /*15*/ "Act as if what you do makes a difference. It does.",
  /*16*/ "Fall seven times and stand up eight.",
  /*17*/ "Do what you feel in your heart to be right – for you’ll be criticized anyway.",
  /*18*/ "Limit your 'always' and your 'nevers'.",
  /*19*/ "Nothing is impossible. The word itself says 'I’m possible!'",
  /*20*/ "What we achieve inwardly will change outer reality.",
  /*21*/ "Don’t count the days, make the days count.",
  /*22*/ "We become what we think about.",
  /*23*/ "Do one thing every day that scares you.",
  /*24*/ "Life is what we make it, always has been, always will be.",
  /*25*/ "The best way out is always through.",
  /*26*/ "We may encounter many defeats but we must not be defeated.",
  /*27*/ "Life isn’t about finding yourself. It’s about creating yourself.",
  /*28*/ "Success is how high you bounce when you hit bottom.",
  /*29*/ "The question isn’t who is going to let me; it’s who is going to stop me.",
  /*30*/ "Everything you’ve ever wanted is on the other side of fear.",
  /*31*/ "Be yourself; everyone else is already taken.",
  /*32*/ "Do not let what you cannot do interfere with what you can do.",
  /*33*/ "Do something wonderful, people may imitate it.",
  /*34*/ "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  /*35*/ "Success is getting what you want. Happiness is wanting what you get.",
  /*36*/ "Be a positive energy trampoline – absorb what you need and rebound more back.",
  /*37*/ "When we strive to become better than we are, everything around us becomes better too.",
  /*38*/ "I never lose. Either I win or I learn.",
  /*39*/ "You don’t need to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.",
  /*40*/ "Hardships often prepare ordinary people for an extraordinary destiny.",
  /*41*/ "The best preparation for tomorrow is doing your best today.",
  /*42*/ "Courage is resistance to fear, mastery of fear—not absence of fear.",
  /*43*/ "Success is not how high you have climbed, but how you make a positive difference to the world.",
  /*44*/ "Turn your wounds into wisdom.",
  /*45*/ "Keep your face always toward the sunshine—and shadows will fall behind you.",
  /*46*/ "In a gentle way, you can shake the world.",
  /*47*/ "If you’re going through hell, keep going.",
  /*48*/ "Start where you are. Use what you have. Do what you can.",
  /*49*/ "The best time to plant a tree was 20 years ago. The second best time is now.",
  /*50*/ "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.",
  /*1*/ "The only journey is the one within.",
  /*2*/ "Life is short, and we should respect every moment of it.",
  /*3*/ "In three words I can sum up everything I’ve learned about life: it goes on.",
  /*4*/ "Be so good they can’t ignore you.",
  /*5*/ "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
  /*6*/ "The most difficult thing is the decision to act, the rest is merely tenacity.",
  /*7*/ "Don’t judge each day by the harvest you reap but by the seeds that you plant.",
  /*8*/ "An unexamined life is not worth living.",
  /*9*/ "Do what you love, and you’ll never work another day in your life.",
  /*10*/ "Good things come to people who wait, but better things come to those who go out and get them.",
  /*11*/ "The best revenge is massive success.",
  /*12*/ "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  /*13*/ "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed.",
  /*14*/ "The real opportunity for success lies within the person and not in the job.",
  /*15*/ "Don’t be afraid to give up the good to go for the great.",
  /*16*/ "It is better to fail in originality than to succeed in imitation.",
  /*17*/ "Success is not how high you have climbed, but how you make a positive difference to the world.",
  /*18*/ "Don’t let the fear of losing be greater than the excitement of winning.",
  /*19*/ "Stop chasing the money and start chasing the passion.",
  /*20*/ "Success usually comes to those who are too busy to be looking for it.",
  /*21*/ "Opportunities don’t happen. You create them.",
  /*22*/ "Try not to become a man of success, but rather become a man of value.",
  /*23*/ "Success is walking from failure to failure with no loss of enthusiasm.",
  /*24*/ "Hardships often prepare ordinary people for an extraordinary destiny.",
  /*25*/ "Success is not in what you have, but who you are.",
  /*26*/ "Don’t cry because it’s over, smile because it happened.",
  /*27*/ "Dream big and dare to fail.",
  /*28*/ "The only limit to our realization of tomorrow will be our doubts of today.",
  /*29*/ "Act as if what you do makes a difference. It does.",
  /*30*/ "The secret to getting ahead is getting started.",
  /*31*/ "Happiness lies in the joy of achievement and the thrill of creative effort.",
  /*32*/ "Don’t wait. The time will never be just right.",
  /*33*/ "Do what you can with all you have, wherever you are.",
  /*34*/ "You don’t have to be great to start, but you have to start to be great.",
  /*35*/ "The best way out is always through.",
  /*36*/ "Success is how high you bounce when you hit bottom.",
  /*37*/ "Motivation is what gets you started. Habit is what keeps you going.",
  /*38*/ "Nothing will work unless you do.",
  /*39*/ "Go confidently in the direction of your dreams. Live the life you have imagined.",
  /*40*/ "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  /*41*/ "Opportunities are usually disguised as hard work, so most people don’t recognize them.",
  /*42*/ "Don’t be afraid to give up the good to go for the great.",
  /*43*/ "Success is not the key to happiness. Happiness is the key to success.",
  /*44*/ "Be yourself; everyone else is already taken.",
  /*45*/ "The road to success and the road to failure are almost exactly the same.",
  /*46*/ "You must be the change you wish to see in the world.",
  /*47*/ "Nothing is impossible, the word itself says ‘I’m possible’!",
  /*48*/ "If you want to achieve greatness, stop asking for permission.",
  /*49*/ "Dream as if you’ll live forever. Live as if you’ll die today.",
  /*50*/ "Strive not to be a success, but rather to be of value.",
  /*51*/ "The best preparation for tomorrow is doing your best today.",
  /*1*/ "The only way to do great work is to love what you do.",
  /*2*/ "In the middle of every difficulty lies opportunity.",
  /*3*/ "Life is what happens when you're busy making other plans.",
  /*4*/ "The web is a very competitive space; you have to be exceptional to stand out.",
  /*5*/ "Challenges are opportunities in disguise; embrace them.",
  /*6*/ "Success is not final; failure is not fatal: It is the courage to continue that counts.",
  /*7*/ "The only limit to our realization of tomorrow is our doubts of today.",
  /*8*/ "Do not wait to strike till the iron is hot; but make it hot by striking.",
  /*9*/ "Whether you think you can or you think you can't, you're right.",
  /*10*/ "The best way to predict the future is to invent it.",
  /*11*/ "I have not failed. I've just found 10,000 ways that won't work.",
  /*12*/ "It does not matter how slowly you go as long as you do not stop.",
  /*13*/ "If you are going through hell, keep going.",
  /*14*/ "Believe you can and you're halfway there.",
  /*15*/ "The only person you are destined to become is the person you decide to be.",
  /*16*/ "Your time is limited, don't waste it living someone else's life.",
  /*17*/ "The purpose of our lives is to be happy.",
  /*18*/ "Get busy living or get busy dying.",
  /*19*/ "You only live once, but if you do it right, once is enough.",
  /*20*/ "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  /*21*/ "If life were predictable it would cease to be life, and be without flavor.",
  /*22*/ "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
  /*23*/ "In order to write about life first you must live it.",
  /*24*/ "The big lesson in life, baby, is never be scared of anyone or anything.",
  /*25*/ "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.",
  /*26*/ "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.",
  /*27*/ "Life is not a problem to be solved, but a reality to be experienced.",
  /*28*/ "The unexamined life is not worth living.",
  /*29*/ "Turn your wounds into wisdom.",
  /*30*/ "The way I see it, if you want the rainbow, you gotta put up with the rain.",
  /*31*/ "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.",
  /*32*/ "Don't settle for what life gives you; make life better and build something.",
  /*33*/ "Everything negative – pressure, challenges – is all an opportunity for me to rise.",
  /*34*/ "I like criticism. It makes you strong.",
  /*35*/ "You never really learn much from hearing yourself speak.",
  /*36*/ "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.",
  /*37*/ "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.",
  /*38*/ "Live for each second without hesitation.",
  /*39*/ "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  /*40*/ "Life is really simple, but men insist on making it complicated.",
  /*41*/ "Life is a succession of lessons which must be lived to be understood.",
  /*42*/ "My mama always said, life is like a box of chocolates. You never know what you're gonna get.",
  /*43*/ "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny.",
  /*44*/ "When we do the best we can, we never know what miracle is wrought in our life or the life of another.",
  /*45*/ "The healthiest response to life is joy.",
  /*46*/ "Life is short, and it is up to you to make it sweet.",
  /*47*/ "You have within you right now, everything you need to deal with whatever the world can throw at you.",
  /*48*/ "Believe that life is worth living and your belief will help create the fact.",
  /*49*/ "The only impossible journey is the one you never begin."
];
var authors = [
  /*1*/ "Buddha",
  /*2*/ "Bruce Lee",
  /*3*/ "Aristotle",
  /*4*/ "Helen Keller",
  /*5*/ "Theodore Roosevelt",
  /*6*/ "Napoleon Hill",
  /*7*/ "Robert F. Kennedy",
  /*8*/ "Oprah Winfrey",
  /*9*/ "Robert Collier",
  /*10*/ "John D. Rockefeller",
  /*11*/ "John Wooden",
  /*12*/ "Charles Kingsleigh (Alice in Wonderland)",
  /*13*/ "Eleanor Roosevelt",
  /*14*/ "Christian D. Larson",
  /*15*/ "Booker T. Washington",
  /*16*/ "Steve Jobs",
  /*17*/ "Eleanor Roosevelt",
  /*18*/ "C.S. Lewis",
  /*19*/ "Confucius",
  /*20*/ "Confucius",
  /*21*/ "Buddha",
  /*22*/ "Mahatma Gandhi",
  /*23*/ "Muhammad Ali",
  /*24*/ "W.P. Kinsella",
  /*25*/ "Pablo Picasso",
  /*26*/ "Ralph Waldo Emerson",
  /*27*/ "Ernest Hemingway",
  /*28*/ "Roy T. Bennett",
  /*29*/ "Charles Dickens",
  /*30*/ "Oprah Winfrey",
  /*31*/ "Ernest Hemingway",
  /*32*/ "Unknown",
  /*33*/ "Sarah Louise Delany",
  /*34*/ "Aristotle",
  /*35*/ "Mark Zuckerberg",
  /*36*/ "Nelson Mandela",
  /*37*/ "Dwayne Johnson",
  /*38*/ "Jim Rohn",
  /*39*/ "Colin R. Davis",
  /*40*/ "Charles Darwin",
  /*41*/ "Marilyn Monroe",
  /*42*/ "Jim Rohn",
  /*43*/ "Robert Frost",
  /*44*/ "George Bernard Shaw",
  /*45*/ "Jimmy Johnson",
  /*46*/ "Eleanor Roosevelt",
  /*47*/ "Albert Schweitzer",
  /*48*/ "Ann Landers",
  /*49*/ "Joshua J. Marine",
  /*50*/ "Abraham Lincoln",
  /*1*/ "Maya Angelou",
  /*2*/ "Dalai Lama",
  /*3*/ "Mahatma Gandhi",
  /*4*/ "Unknown",
  /*5*/ "Napoleon Hill",
  /*6*/ "Theodore Roosevelt",
  /*7*/ "Michael Jordan",
  /*8*/ "Eleanor Roosevelt",
  /*9*/ "Arthur Ashe",
  /*10*/ "Nelson Mandela",
  /*11*/ "Babe Ruth",
  /*12*/ "Walt Disney",
  /*13*/ "John D. Rockefeller Jr.",
  /*14*/ "Unknown",
  /*15*/ "Marva Collins",
  /*16*/ "Jim Ryun",
  /*17*/ "Frank Sinatra",
  /*18*/ "Bo Bennett",
  /*19*/ "Will Rogers",
  /*20*/ "Chris Grosser",
  /*21*/ "Napoleon Hill",
  /*22*/ "A.A. Milne",
  /*23*/ "Buddha",
  /*24*/ "Henry David Thoreau",
  /*25*/ "Michael John Bobak",
  /*26*/ "Richard Branson",
  /*27*/ "Bill Bradley",
  /*28*/ "Estée Lauder",
  /*29*/ "Michelle Obama",
  /*30*/ "Unknown",
  /*31*/ "Franklin D. Roosevelt",
  /*32*/ "Ziad K. Abdelnour",
  /*33*/ "Franklin D. Roosevelt",
  /*34*/ "Mark Twain",
  /*35*/ "Vince Lombardi",
  /*36*/ "Eleanor Roosevelt",
  /*37*/ "Mark Twain",
  /*38*/ "Zig Ziglar",
  /*39*/ "Serena Williams",
  /*40*/ "Confucius",
  /*41*/ "Japanese Proverb",
  /*42*/ "Steve Jobs",
  /*43*/ "Theodore Roosevelt",
  /*44*/ "Confucius",
  /*45*/ "Walt Whitman",
  /*46*/ "Sun Tzu",
  /*47*/ "Vincent Van Gogh",
  /*48*/ "John Lennon",
  /*49*/ "Albert Einstein",
  /*50*/ "William James",
  /*1*/ "Sam Levenson",
  /*2*/ "Napoleon Hill",
  /*3*/ "Vidal Sassoon",
  /*4*/ "Jimmy Dean",
  /*5*/ "Walter Elliot",
  /*6*/ "Tony Robbins",
  /*7*/ "Aristotle",
  /*8*/ "Christian D. Larson",
  /*9*/ "Henry David Thoreau",
  /*10*/ "Albert Einstein",
  /*11*/ "George Washington",
  /*12*/ "Chris Grosser",
  /*13*/ "John D. Rockefeller",
  /*14*/ "Bo Bennett",
  /*15*/ "William James",
  /*16*/ "Japanese Proverb",
  /*17*/ "Eleanor Roosevelt",
  /*18*/ "Amy Poehler",
  /*19*/ "Audrey Hepburn",
  /*20*/ "Plutarch",
  /*21*/ "Muhammad Ali",
  /*22*/ "Earl Nightingale",
  /*23*/ "Eleanor Roosevelt",
  /*24*/ "Grandma Moses",
  /*25*/ "Robert Frost",
  /*26*/ "Maya Angelou",
  /*27*/ "George Bernard Shaw",
  /*28*/ "George S. Patton",
  /*29*/ "Ayn Rand",
  /*30*/ "George Addair",
  /*31*/ "Oscar Wilde",
  /*32*/ "John Wooden",
  /*33*/ "Albert Schweitzer",
  /*34*/ "Zig Ziglar",
  /*35*/ "W.P. Kinsella",
  /*36*/ "Dave Carolan",
  /*37*/ "Paulo Coelho",
  /*38*/ "Nelson Mandela",
  /*39*/ "Ziad K. Abdelnour",
  /*40*/ "C.S. Lewis",
  /*41*/ "H. Jackson Brown, Jr.",
  /*42*/ "Mark Twain",
  /*43*/ "Roy T. Bennett",
  /*44*/ "Oprah Winfrey",
  /*45*/ "Walt Whitman",
  /*46*/ "Mahatma Gandhi",
  /*47*/ "Winston Churchill",
  /*48*/ "Arthur Ashe",
  /*49*/ "Chinese Proverb",
  /*50*/ "Orison Swett Marden",
  /*1*/ "Sam Levenson",
  /*2*/ "Napoleon Hill",
  /*3*/ "Vidal Sassoon",
  /*4*/ "Jimmy Dean",
  /*5*/ "Walter Elliot",
  /*6*/ "Tony Robbins",
  /*7*/ "Aristotle",
  /*8*/ "Christian D. Larson",
  /*9*/ "Henry David Thoreau",
  /*10*/ "Albert Einstein",
  /*11*/ "George Washington",
  /*12*/ "Chris Grosser",
  /*13*/ "John D. Rockefeller",
  /*14*/ "Bo Bennett",
  /*15*/ "William James",
  /*16*/ "Japanese Proverb",
  /*17*/ "Eleanor Roosevelt",
  /*18*/ "Amy Poehler",
  /*19*/ "Audrey Hepburn",
  /*20*/ "Plutarch",
  /*21*/ "Muhammad Ali",
  /*22*/ "Earl Nightingale",
  /*23*/ "Eleanor Roosevelt",
  /*24*/ "Grandma Moses",
  /*25*/ "Robert Frost",
  /*26*/ "Maya Angelou",
  /*27*/ "George Bernard Shaw",
  /*28*/ "George S. Patton",
  /*29*/ "Ayn Rand",
  /*30*/ "George Addair",
  /*31*/ "Oscar Wilde",
  /*32*/ "John Wooden",
  /*33*/ "Albert Schweitzer",
  /*34*/ "Zig Ziglar",
  /*35*/ "W.P. Kinsella",
  /*36*/ "Dave Carolan",
  /*37*/ "Paulo Coelho",
  /*38*/ "Nelson Mandela",
  /*39*/ "Ziad K. Abdelnour",
  /*40*/ "C.S. Lewis",
  /*41*/ "H. Jackson Brown, Jr.",
  /*42*/ "Mark Twain",
  /*43*/ "Roy T. Bennett",
  /*44*/ "Oprah Winfrey",
  /*45*/ "Walt Whitman",
  /*46*/ "Mahatma Gandhi",
  /*47*/ "Winston Churchill",
  /*48*/ "Arthur Ashe",
  /*49*/ "Chinese Proverb",
  /*50*/ "Orison Swett Marden",
  /*1*/ "Rainer Maria Rilke",
  /*2*/ "Orhan Pamuk",
  /*3*/ "Robert Frost",
  /*4*/ "Steve Martin",
  /*5*/ "Ayn Rand",
  /*6*/ "Amelia Earhart",
  /*7*/ "Robert Louis Stevenson",
  /*8*/ "Socrates",
  /*9*/ "Marc Anthony",
  /*10*/ "Anonymous",
  /*11*/ "Frank Sinatra",
  /*12*/ "Jim Rohn",
  /*13*/ "Tony Robbins",
  /*14*/ "Zig Ziglar",
  /*15*/ "John D. Rockefeller",
  /*16*/ "Herman Melville",
  /*17*/ "Roy T. Bennett",
  /*18*/ "Robert Kiyosaki",
  /*19*/ "Tony Hsieh",
  /*20*/ "Henry David Thoreau",
  /*21*/ "Chris Grosser",
  /*22*/ "Albert Einstein",
  /*23*/ "Winston Churchill",
  /*24*/ "C.S. Lewis",
  /*25*/ "Bo Bennett",
  /*26*/ "Dr. Seuss",
  /*27*/ "Norman Vaughan",
  /*28*/ "Franklin D. Roosevelt",
  /*29*/ "William James",
  /*30*/ "Mark Twain",
  /*31*/ "Franklin D. Roosevelt",
  /*32*/ "Napoleon Hill",
  /*33*/ "Theodore Roosevelt",
  /*34*/ "Zig Ziglar",
  /*35*/ "Robert Frost",
  /*36*/ "George S. Patton",
  /*37*/ "Jim Ryun",
  /*38*/ "Maya Angelou",
  /*39*/ "Henry David Thoreau",
  /*40*/ "Winston Churchill",
  /*41*/ "Ann Landers",
  /*42*/ "John D. Rockefeller",
  /*43*/ "Albert Schweitzer",
  /*44*/ "Oscar Wilde",
  /*45*/ "Colin R. Davis",
  /*46*/ "Mahatma Gandhi",
  /*47*/ "Audrey Hepburn",
  /*48*/ "Anonymous",
  /*49*/ "James Dean",
  /*50*/ "Albert Einstein",
  /*51*/ "H. Jackson Brown, Jr.",
    /*1*/ "Steve Jobs",
  /*2*/ "Albert Einstein",
  /*3*/ "John Lennon",
  /*4*/ "Chris Coyier",
  /*5*/ "Ngozi Okonjo-Iweala",
  /*6*/ "Winston Churchill",
  /*7*/ "Franklin D. Roosevelt",
  /*8*/ "William Butler Yeats",
  /*9*/ "Henry Ford",
  /*10*/ "Alan Kay",
  /*11*/ "Thomas Edison",
  /*12*/ "Confucius",
  /*13*/ "Winston Churchill",
  /*14*/ "Theodore Roosevelt",
  /*15*/ "Ralph Waldo Emerson",
  /*16*/ "Steve Jobs",
  /*17*/ "Dalai Lama",
  /*18*/ "Stephen King",
  /*19*/ "Mae West",
  /*20*/ "Thomas Edison",
  /*21*/ "Eleanor Roosevelt",
  /*22*/ "Henry Ford",
  /*23*/ "Ernest Hemingway",
  /*24*/ "Frank Sinatra",
  /*25*/ "Attributed to various sources",
  /*26*/ "Leo Burnett",
  /*27*/ "Soren Kierkegaard",
  /*28*/ "Socrates",
  /*29*/ "Oprah Winfrey",
  /*30*/ "Dolly Parton",
  /*31*/ "Hillary Clinton",
  /*32*/ "Ashton Kutcher",
  /*33*/ "Kobe Bryant",
  /*34*/ "LeBron James",
  /*35*/ "George Clooney",
  /*36*/ "Celine Dion",
  /*37*/ "John F. Kennedy",
  /*38*/ "Elton John",
  /*39*/ "Albert Einstein",
  /*40*/ "Confucius",
  /*41*/ "Ralph Waldo Emerson",
  /*42*/ "Forrest Gump",
  /*43*/ "Lao-Tze",
  /*44*/ "Helen Keller",
  /*45*/ "Deepak Chopra",
  /*46*/ "Sarah Louise Delany",
  /*47*/ "Brian Tracy",
  /*48*/ "William James",
  /*49*/ "Tony Robbins"
];