var quotes =[
 /*1*/"Believe You can and you are half way there",
 /*2*/"It does no matter how slowly you go as long as you don't stop",
 /*3*/"Success is not final, Failure is not fatal, It is courage to continue that counts.",
 /*4*/"Don't Watch the clock; Do what it does.Keep Going",
 /*5*/"You miss 100% of the sots you dont take",
 /*6*/"I have not failed. I've just found 10,000 Ways that won't work",
 /*7*/"You are not too Old to set another dream or to dream a new dream",
 /*8*/"The Only way to do great work is to love what you do",
 /*9*/"Keep your eyes on the stars, and your feet on the ground",
 /*10*/"You don't have to be great to start , but you have to start to be great",
 /*11*/"Fall Seven times, Stand up Eight",
 /*12*/"When you come to the end of your rope, tie a knot and hang on",
 /*13*/"Life is 10% what happens to you and 90% how you react to it",
 /*14*/"Do not let what you cannot do interfere with what you can do",
 /*15*/"You are stronger than you seem, braver than you believe, and smarter than you think",
 /*16*/"You can't go back and change the ending",
 /*17*/"Invest in yourself, it's the best investment you'll ever make",
 /*18*/"A journey of a thousand miles begins with a single step.",
 /*19*/"Do something today that your future self will thank you for",
 /*20*/"You are the architect of your own destiny",
 /*21*/"Procrastination is like a credit card; it's a lot of fun until you get the bill",
 /*22*/"The best way to get started is to quit talking and doing",
 /*23*/"Time is money",
 /*24*/"The only limit to our realization of tomorrow is today",
 /*25*/"You don't have to see the whole staircase, just take the first step",
 /*26*/"Leadership is not about titles, positions or flowcharts.It is about one life influencing another",
 /*27*/"A leader is one who knows the way, goes the way and shows the way",
 /*28*/"The greatest leaders mobilize others by coalescing people around a shared sense of purpose",
 /*29*/"Leadership is the capacity to translate vision into reality",
 /*30*/"You manage things; you lead people",
 /*31*/"The Purpose of life is to find your gift, The meaning of  life is to give it away",
 /*32*/"Your time is so limited, so don't waste it living someone else life ", 
 /*33*/"The best way to find yourself is to lose yourself in the service of others",
 /*34*/"Life begins at the end of your comfort zone",
 /*35*/"You are put in this earth to achieve your greatest self",
 /*36*/"Life doesn't get easier or more forgiving, we get stronger and more resilient",
 /*37*/"The greatest glory in living lies not in never falling, but rising everytime we fall",
 /*38*/"You are stonger than you seem, braver than you believe and smarter than you think",
 /*39*/"Happiness is not something ready made, It comes from your own actions",
 /*40*/"The happiest people don't have the best of everything, but make the best of everything", 
 /*41*/"Faith is the art of holding on to things your reason has once accepted, in spite of your changing moods.",
 /*42*/"The soul should always stand ajar, ready to welcome the ecstatic experience.",
 /*43*/"We are shaped and fashioned by what we love.",
 /*44*/"The most important thing in life is to learn how to give out love, and let it come in.",
 /*45*/"You pray in your distress and in your need; would that you might pray also in your fullness and in your success.",
 /*46*/"The highest wisdom is to understand that all men are mad.",
 /*47*/"Love is the only force capable of transforming an enemy into a friend.",
 /*48*/"A man's true wealth is the good he does in the world.", 
 /*49*/"We must become the change we wish to see in the world.",
 /*50*/"The greatest discovery of all time is that a person can change their future by merely changing their attitude.",
 /*51*/"Life has no other discipline to impose . . . if we instantaneously feel what we think.",
 /*52*/"You alone are enough. You have nothing to prove to anyone.",
 /*53*/"No one can find inner peace except by working, not in a self-centered way, but for the whole human family.",
 /*54*/"Spirituality is not about being religious; it's about being humane.",
 /*55*/"God is not a destination; God is the journey.",
 /*56*/"You can't separate peace from freedom because no one can be at peace unless he has his freedom.",
 /*57*/"Happiness is when what you think, what you say, and what you do are in harmony.",
 /*58*/"The ultimate value of life depends upon awareness and the power of contemplation rather than upon mere survival.",
 /*59*/"The soul that sees beauty may sometimes walk alone.",
 /*60*/"Our true nature is not limited to the conditioned and the known; we are also the unknown.",
 /*61*/"Spirituality does not mean living in the mountains; spirituality means living in the world but beyond the world.",
 /*62*/"To be a saint is to be grounded, courageous, and kind.",
 /*63*/"You don't have to control your thoughts. You just have to stop letting them control you.",
 /*64*/"We are all here for some particular purpose.",
 /*65*/"The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",
 /*66*/"The biggest adventure you can take is to live the life of your dreams.",
 /*67*/"Do not let the world dictate your inner pace.",
 /*68*/"You are here to enable the divine purpose of the universe to unfold.",
 /*69*/"The present moment is the only moment available to us, and it is the door to all moments.",
 /*70*/"To love oneself is the beginning of a lifelong romance.",
 /*71*/"The only thing that will stop you from fulfilling your dreams is you.",
 /*72*/"We must let go of the life we have planned, so as to accept the one that is waiting for us.",
 /*73*/"The best revenge is massive success.",
 /*74*/"You are not responsible for the programming you picked up as a child.",
 /*75*/"Your sacred space is where you can find yourself again and again.",
 /*76*/"The future belongs to those who believe in the beauty of their dreams",
 /*77*/"A people without knowledge of their past history, origin and culture is like a tree without roots.",
 /*78*/"The best way to predict your future is to create it.",
 /*79*/"Challenges are the catalysts for growth.",
 /*80*/"We must cultivate the art of being able to look beyond the immediate.",
 /*81*/"The greatest wealth is health.",
 /*82*/"You mustn't be afraid to dream big.", 
 /*83*/"The only thing necessary for the triumph of evil is for good men to do nothing.",
 /*84*/"It always seems impossible until it's done.",
 /*85*/"The key to success is action, and the essential in action is perseverance.",
 /*86*/"The man who moves a mountain begins by carrying away small stones.",
 /*87*/"The superior man is modest in his speech, but exceeds in his actions.",
 /*88*/"Do not go where the path may lead; go instead where there is no path and leave a trail.",
 /*89*/"The whole is more than the sum of its parts.",
 /*90*/"When the winds of change blow, some people build walls, and others build windmills.", 
 /*91*/"A single grain of rice can tip the scale.",
 /*92*/"One should not hunt man; one should hunt what makes one man.",
 /*93*/"The wise adapt themselves to circumstances, as water shapes itself to the vessel.",
 /*94*/"To know what you know and what you do not know, that is true knowledge.",
 /*95*/"Nature does not hurry, yet everything is accomplished.",
 /*96*/"He who knows does not speak. He who speaks does not know.",
 /*97*/"The softest thing in the world overcomes the hardest thing in the world.",
 /*98*/"Virtue is not left to stand alone. He who practices it will have neighbors.", 
 /*99*/"Be not afraid of growing slowly, be afraid only of standing still.",
 /*100*/"The superior man is distressed by the limitations of his ability, but he is not distressed by the fact that men do not recognize his ability.", 
  /*101*/"The man who is master of himself is more powerful than one who has a thousand horsemen at his command.", 
 /*102*/"When anger rises, think of the consequences.",
 /*103*/"To see the right and not to do it is cowardice.",
 /*104*/"The noble-minded are calm and steady.",
 /*105*/"He who wishes to be filial cannot but show respect to his elders.",
 /*106*/"Know yourself and know your enemy, and you will win a hundred battles.",
 /*107*/"The superior man seeks to perfect his character, and seeks for its development by careful self-examination.",
 /*108*/"Wealth brings many friends, but poverty drives them away.",
 /*109*/"Do not worry about being exploited; worry about failing to exploit your full potential.",
 /*110*/"He who learns but does not think is lost. He who thinks but does not learn is in great danger.",
 /*111*/"When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.",
 /*112*/"The superior man makes the difficulty to be overcome his first interest.",
 /*113*/"Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them.",
 /*114*/"The Internet is a powerful tool for social change, but it's not a substitute for real-world action.",
 /*115*/"Software is like entropy: it constantly needs to be reorganized, rewritten, or replenished.",
 /*116*/"Information technology and business are becoming inextricably interwoven.",
 /*117*/"The future of technology is not just about smartphones, it's about artificial intelligence, robotics, and biotechnology.",
 /*118*/"The best way to predict the future is to invent it.",
 /*119*/"Innovation distinguishes between a leader and a follower.",
 /*120*/"The cyberattack on one nation is an attack on all nations.",
 /*121*/"The biggest risk is not taking any risk.",
 /*122*/"Technology should support humans, not replace them.",
 /*123*/"Artificial intelligence will reach human intelligence levels by 2029.",
 /*124*/"Cybersecurity is not just a technical issue, it's a boardroom issue.",
 /*125*/"Digital divide is a threat to global stability.",
 /*126*/"The cloud is the new operating system.",
 /*127*/"Mobile is the future of the Internet.",
 /*128*/"Social media has made it easier to spread misinformation.",
 /*129*/"Blockchain is the backbone of the Internet of Value.",
 /*130*/"Artificial intelligence will change the world more than electricity.",
 /*131*/"Code is poetry",
 /*132*/"The web is a very competitive space; you have to be exceptional to stand out.",
 /*133*/"Web development is not just coding, it's problem-solving.",
 /*134*/"A website without a conversion rate optimization strategy is like a store without salespeople.",
 /*135*/"Web performance is user experience.",
 /*136*/"Accessibility is not a feature, it's a fundamental aspect of web design.",
 /*137*/"Code is like humor. When you have to explain it, it’s bad",
 /*138*/"Coding is today's language of creativity.",
 /*139*/"The best coders are the ones who can make complex things simple.",
 /*140*/"Code quality is directly correlated with developer quality.",
 /*141*/"Design is not just what it looks like and feels like. Design is how it works",
 /*142*/"The best design is the design that you don’t notice.",
 /*143*/"Web design is not just about making pretty pictures, it's about making user experiences.",
 /*144*/"Simplicity is the ultimate form of sophistication.",
 /*145*/"Designing a product is designing a relationship.",
 /*146*/"The music we listen to may not define us, but it's a representation of who we are.",
 /*147*/"Words have the power to heal and harm; use them wisely.",
 /*148*/"In drama and poetry, we find the essence of humanity.",
 /*149*/"The world is a stage, and life is a script we write every day.",
 /*150*/"Faith is the Substance of things hoped for"

];
var authors=[
 /*1*/"Theodore Roosevelt",
 /*2*/"Confucius",
 /*3*/"Winston Churchill",
 /*4*/"Sam Levnson",
 /*5*/"Wayne Gretzky",
 /*6*/"Thomas Edison",
 /*7*/"C.S Lewis",
 /*8*/"Steve Jobs",
 /*9*/"Theodore Roosevelt",
 /*10*/"Zig Ziglar",
 /*11*/"Japanese Proverb",
 /*12*/"Franklin D.Roosevelt",
 /*13*/"Charles R.Swindoll",
 /*14*/"John Wooden",
 /*15*/"Christopher Robin",
 /*16*/"C.S Lewis",
 /*17*/"Unknown",
 /*18*/"Lao Tzu",
 /*19*/"Unknown",
 /*20*/"Lailah Gifty Akita",
 /*21*/"Christopher Parker",
 /*22*/"Walt Disney",
 /*23*/"Benjamin Franklin",
 /*24*/"Franklin D.Roosevelt",
 /*25*/"Martin Luther King Jr.",
 /*26*/"John C. Maxwell",
 /*27*/"John C. Maxwell",
 /*28*/"Ken Blanchard",
 /*29*/"Warren Bennis",
 /*30*/"Rear admiral G.H",
 /*31*/"Pablo Picasso",
 /*32*/"Steve Jobs",
 /*33*/"Mahatma Ghandi",
 /*34*/"Neale Donald Walsh",
 /*35*/"Unknown",
 /*36*/"Steve Maraboli",
 /*37*/"Nelson Mandela",
 /*38*/"Christopher Robin",
 /*39*/"Dalai Lama",
 /*40*/"Unknown", 
 /*41*/"C.S. Lewis",
 /*42*/"Emily Dickinson",
 /*43*/"Johann Wolfgang V.G",
 /*44*/"Morrie Schwartz",
 /*45*/"Khalil Gibran",
 /*46*/"Diogenes",
 /*47*/"Martin Luther King Jr.",
 /*48*/"Kahlil Gibran", 
 /*49*/"Mahatma Gandhi",
 /*50*/"Oprah Winfrey",
 /*51*/"Sri Aurobindo",
 /*52*/"Maya Angelou",
 /*53*/"Dalai Lama XIV",
 /*54*/"Unknown",
 /*55*/"Deepak Chopra",
 /*56*/"Malcolm X",
 /*57*/"Mahatma Gandhi",
 /*58*/"Aristotle",
 /*59*/"Johann Wolfgang V.G",
 /*60*/"Adyashanti",
 /*61*/"Osho",
 /*62*/"Unknown",
 /*63*/"Dan Millman",
 /*64*/"Vincent van Gogh",
 /*65*/"Ralph Waldo Emerson",
 /*66*/"Oprah Winfrey",
 /*67*/"Unknown",
 /*68*/"Caroline Myss",
 /*69*/"Thich Nhat Hanh",
 /*70*/"Oscar Wilde",
 /*71*/"Tom Bradley",
 /*72*/"E.M. Forster",
 /*73*/"Frank Sinatra",
 /*74*/"Dr. Hew Len",
 /*75*/"Joseph Campbell",
 /*76*/"Hakeem Baba-Ahmad",
 /*77*/"Michael Imoudu",
 /*78*/"Aliko Dangote",
 /*79*/"Ngozi Okonjo-Iweala",
 /*80*/"Olusegun Obasanjo",
 /*81*/"Wole Soyinka",
 /*82*/"Fela Kuti", 
 /*83*/"Joseph Dosu",
 /*84*/"Yakubu Gowon",
 /*85*/"Murtala Mohammed",
 /*86*/"Confucius",
 /*87*/"Confucius",
 /*88*/"Mencius",
 /*89*/"Lao Tzu",
 /*90*/"Chinese Proverb", 
 /*91*/"Chinese Proverb",
 /*92*/"Lao She",
 /*93*/"Confucius",
 /*94*/"Confucius",
 /*95*/"Lao Tzu",
 /*96*/"Lao Tzu",
 /*97*/"Lao Tzu",
 /*98*/"Confucius", 
 /*99*/"Chinese Proverb",
 /*100*/"Confucius",
 /*101*/"Chinese Proverb", 
 /*102*/"Confucius",
 /*103*/"Confucius",
 /*104*/"Confucius",
 /*105*/"Chinese Proverb",
 /*106*/"Sun Tzu",
 /*107*/"Confucius",
 /*108*/"Chinese Proverb",
 /*109*/"Chinese Proverb",
 /*110*/"Confucius",
 /*111*/"Confucius",
 /*112*/"Confucius",
 /*113*/"Steve Jobs",
 /*114*/"Steven Johnson",
 /*115*/"Nick Farrell",
 /*116*/"Bill Gates",
 /*117*/"Masayoshi Son",
 /*118*/"Alan Kay",
 /*119*/"Steve Jobs",
 /*120*/"Ban Ki-moon",
 /*121*/"Mark Zuckerberg",
 /*122*/"Jaron Lanier",
 /*123*/"Ray Kurzweil",
 /*124*/"CISA",
 /*125*/"Kofi Annan",
 /*126*/"Marc Benioff",
 /*127*/"Eric Schmidt",
 /*128*/"Eli Pariser",
 /*129*/"Don Tapscott",
 /*130*/"AI Today podcast",
 /*131*/"Adedokun Precious",
 /*132*/"Chris Coyier",
 /*133*/"Adedokun Precious",
 /*134*/"Adedokun Precious",
 /*135*/"Lara Hogan",
 /*136*/"Derek Featherstone",
 /*137*/"Cory House",
 /*138*/"Abhinav Chhikara",
 /*139*/"Adedokun Precious",
 /*140*/"Jeff Atwood",
 /*141*/"Steve Jobs",
 /*142*/"Dan Cederholm",
 /*143*/"Vitaly Friedman",
 /*144*/"John Maeda",
 /*145*/"Jonathan Ive",
 /*146*/"Katy Perry",
 /*147*/"Unknown",
 /*148*/"Unknown",
 /*149*/"Unknown",
 /*150*/"Pst E.A Adeboye"
];