const quotes = [
    { quote: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
    { quote: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { quote: "Happiness depends upon ourselves.", author: "Aristotle" },
    { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
    { quote: "Do what you can with what you have where you are.", author: "Theodore Roosevelt" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { quote: "Only those who dare to fail greatly can ever achieve greatly.", author: "Robert F. Kennedy" },
    { quote: "The more you praise and celebrate your life, the more there is in life to celebrate.", author: "Oprah Winfrey" },
    { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh (Alice in Wonderland)" },
    { quote: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt" },
    { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { quote: "Success is not measured by the position one has reached in life, rather by the obstacles one overcomes while trying to succeed.", author: "Booker T. Washington" },
    { quote: "Don’t let the noise of others’ opinions drown out your own inner voice.", author: "Steve Jobs" },
    { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
    { quote: "What we think, we become.", author: "Buddha" },
    { quote: "The future depends on what you do today.", author: "Mahatma Gandhi" },
    { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "W.P. Kinsella" },
    { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
    { quote: "Courage is grace under pressure.", author: "Ernest Hemingway" },
    { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { quote: "Life is made of ever so many partings welded together.", author: "Charles Dickens" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "In order to write about life, first you must live it.", author: "Ernest Hemingway" },
    { quote: "You are the artist of your own life. Don’t hand the paintbrush to anyone else.", author: "Unknown" },
    { quote: "Life is short, and it’s up to you to make it sweet.", author: "Sarah Louise Delany" },
    { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
    { quote: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "Success isn’t overnight. It’s when every day you get a little better than the day before. It all adds up.", author: "Dwayne Johnson" },
    { quote: "Don’t wish it were easier. Wish you were better.", author: "Jim Rohn" },
    { quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { quote: "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.", author: "Charles Darwin" },
    { quote: "Keep smiling, because life is a beautiful thing and there’s so much to smile about.", author: "Marilyn Monroe" },
    { quote: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn" },
    { quote: "The best way out is always through.", author: "Robert Frost" },
    { quote: "Life isn’t about finding yourself. It’s about creating yourself.", author: "George Bernard Shaw" },
    { quote: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
    { quote: "Do what you feel in your heart to be right – for you’ll be criticized anyway.", author: "Eleanor Roosevelt" },
    { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { quote: "Opportunities are usually disguised as hard work, so most people don’t recognize them.", author: "Ann Landers" },
    { quote: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine" },
    { quote: "It’s not the years in your life that count. It’s the life in your years.", author: "Abraham Lincoln" }
  ];

  const quotes = [
    { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    { quote: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
    { quote: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { quote: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { quote: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
    { quote: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { quote: "Don’t let the fear of striking out hold you back.", author: "Babe Ruth" },
    { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { quote: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
    { quote: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
    { quote: "Success doesn’t come to you. You go to it.", author: "Marva Collins" },
    { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    { quote: "Your big opportunity may be right where you are now.", author: "Napoleon Hill" },
    { quote: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
    { quote: "No matter how hard the past, you can always begin again.", author: "Buddha" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { quote: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
    { quote: "Do not be embarrassed by your failures, learn from them and start again.", author: "Richard Branson" },
    { quote: "Ambition is the path to success. Persistence is the vehicle you arrive in.", author: "Bill Bradley" },
    { quote: "I never dreamed about success, I worked for it.", author: "Estée Lauder" },
    { quote: "Success isn’t about how much money you make; it’s about the difference you make in people’s lives.", author: "Michelle Obama" },
    { quote: "The harder you work for something, the greater you’ll feel when you achieve it.", author: "Unknown" },
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "You don’t have to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.", author: "Ziad K. Abdelnour" },
    { quote: "Happiness lies in the joy of achievement and the thrill of creative effort.", author: "Franklin D. Roosevelt" },
    { quote: "Courage is resistance to fear, mastery of fear, not absence of fear.", author: "Mark Twain" },
    { quote: "It’s not whether you get knocked down; it’s whether you get up.", author: "Vince Lombardi" },
    { quote: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
    { quote: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { quote: "A champion is defined not by their wins but by how they can recover when they fall.", author: "Serena Williams" },
    { quote: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
    { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { quote: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
    { quote: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
    { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
    { quote: "What would life be if we had no courage to attempt anything?", author: "Vincent Van Gogh" },
    { quote: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
    { quote: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" }
  ];

  const quotes = [
    { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { quote: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { quote: "Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", author: "Albus Dumbledore (J.K. Rowling)" },
    { quote: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
    { quote: "What you do makes a difference, and you have to decide what kind of difference you want to make.", author: "Jane Goodall" },
    { quote: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
    { quote: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { quote: "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit.", author: "Conrad Hilton" },
    { quote: "To accomplish great things, we must not only act, but also dream, not only plan, but also believe.", author: "Anatole France" },
    { quote: "You define your own life. Don’t let other people write your script.", author: "Oprah Winfrey" },
    { quote: "Life is short, and it’s up to you to make it sweet.", author: "Sarah Louise Delany" },
    { quote: "You are enough just as you are.", author: "Meghan Markle" },
    { quote: "Nothing will work unless you do.", author: "Maya Angelou" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "Stay close to anything that makes you glad you are alive.", author: "Hafez" },
    { quote: "Don’t cry because it’s over, smile because it happened.", author: "Dr. Seuss" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { quote: "Everything has beauty, but not everyone can see it.", author: "Confucius" },
    { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { quote: "We can do anything we want to if we stick to it long enough.", author: "Helen Keller" },
    { quote: "Nothing is impossible, the word itself says 'I’m possible'!", author: "Audrey Hepburn" },
    { quote: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { quote: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.", author: "Vivian Greene" },
    { quote: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
    { quote: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
    { quote: "Opportunities don’t happen, you create them.", author: "Chris Grosser" },
    { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    { quote: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
    { quote: "You can’t cross the sea merely by standing and staring at the water.", author: "Rabindranath Tagore" },
    { quote: "Believe in yourself! Have faith in your abilities!", author: "Norman Vincent Peale" },
    { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { quote: "Only I can change my life. No one can do it for me.", author: "Carol Burnett" },
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { quote: "Shoot for the moon. Even if you miss, you’ll land among the stars.", author: "Norman Vincent Peale" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { quote: "You can’t go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "Happiness is not by chance, but by choice.", author: "Jim Rohn" }
  ];

  const quotes = [
    { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { quote: "A goal is a dream with a deadline.", author: "Napoleon Hill" },
    { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    { quote: "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
    { quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
    { quote: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
    { quote: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { quote: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { quote: "Try not to become a person of success, but rather try to become a person of value.", author: "Albert Einstein" },
    { quote: "The harder the conflict, the greater the triumph.", author: "George Washington" },
    { quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { quote: "Do what you feel in your heart to be right – for you’ll be criticized anyway.", author: "Eleanor Roosevelt" },
    { quote: "Limit your 'always' and your 'nevers'.", author: "Amy Poehler" },
    { quote: "Nothing is impossible. The word itself says 'I’m possible!'", author: "Audrey Hepburn" },
    { quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    { quote: "We become what we think about.", author: "Earl Nightingale" },
    { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
    { quote: "The best way out is always through.", author: "Robert Frost" },
    { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
    { quote: "Life isn’t about finding yourself. It’s about creating yourself.", author: "George Bernard Shaw" },
    { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { quote: "The question isn’t who is going to let me; it’s who is going to stop me.", author: "Ayn Rand" },
    { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { quote: "Do something wonderful, people may imitate it.", author: "Albert Schweitzer" },
    { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "W.P. Kinsella" },
    { quote: "Be a positive energy trampoline – absorb what you need and rebound more back.", author: "Dave Carolan" },
    { quote: "When we strive to become better than we are, everything around us becomes better too.", author: "Paulo Coelho" },
    { quote: "I never lose. Either I win or I learn.", author: "Nelson Mandela" },
    { quote: "You don’t need to be perfect to inspire others. Let people get inspired by how you deal with your imperfections.", author: "Ziad K. Abdelnour" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown, Jr." },
    { quote: "Courage is resistance to fear, mastery of fear—not absence of fear.", author: "Mark Twain" },
    { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    { quote: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { quote: "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.", author: "Orison Swett Marden" }
  ];

  const quotes = [
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { quote: "The web is a very competitive space; you have to be exceptional to stand out.", author: "Chris Coyier" },
    { quote: "Challenges are opportunities in disguise; embrace them.", author: "Ngozi Okonjo-Iweala" },
    { quote: "Success is not final; failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
    { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
    { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
    { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { quote: "If you are going through hell, keep going.", author: "Winston Churchill" },
    { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { quote: "Get busy living or get busy dying.", author: "Stephen King" },
    { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    { quote: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
    { quote: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
    { quote: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford" },
    { quote: "In order to write about life first you must live it.", author: "Ernest Hemingway" },
    { quote: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra" },
    { quote: "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.", author: "Attributed to various sources" },
    { quote: "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", author: "Leo Burnett" },
    { quote: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard" },
    { quote: "The unexamined life is not worth living.", author: "Socrates" },
    { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { quote: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton" },
    { quote: "Do all the good you can, for all the people you can, in all the ways you can, as long as you can.", author: "Hillary Clinton" },
    { quote: "Don't settle for what life gives you; make life better and build something.", author: "Ashton Kutcher" },
    { quote: "Everything negative – pressure, challenges – is all an opportunity for me to rise.", author: "Kobe Bryant" },
    { quote: "I like criticism. It makes you strong.", author: "LeBron James" },
    { quote: "You never really learn much from hearing yourself speak.", author: "George Clooney" },
    { quote: "Life imposes things on you that you can’t control, but you still have the choice of how you’re going to live through this.", author: "Celine Dion" },
    { quote: "Life is never easy. There is work to be done and obligations to be met – obligations to truth, to justice, and to liberty.", author: "John F. Kennedy" },
    { quote: "Live for each second without hesitation.", author: "Elton John" },
    { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
    { quote: "Life is really simple, but men insist on making it complicated.", author: "Confucius" },
    { quote: "Life is a succession of lessons which must be lived to be understood.", author: "Ralph Waldo Emerson" },
    { quote: "My mama always said, life is like a box of chocolates. You never know what you're gonna get.", author: "Forrest Gump" },
    { quote: "Watch your thoughts; they become words. Watch your words; they become actions. Watch your actions; they become habits. Watch your habits; they become character. Watch your character; it becomes your destiny.", author: "Lao-Tze" },
    { quote: "When we do the best we can, we never know what miracle is wrought in our life or the life of another.", author: "Helen Keller" },
    { quote: "The healthiest response to life is joy.", author: "Deepak Chopra" },
    { quote: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
    { quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { quote: "Believe that life is worth living and your belief will help create the fact.", author: "William James" },
    { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" }
  ];

  const quotes = [
    { quote: "The only journey is the one within.", author: "Rainer Maria Rilke" },
    { quote: "Life is short, and we should respect every moment of it.", author: "Orhan Pamuk" },
    { quote: "In three words I can sum up everything I’ve learned about life: it goes on.", author: "Robert Frost" },
    { quote: "Be so good they can’t ignore you.", author: "Steve Martin" },
    { quote: "A creative man is motivated by the desire to achieve, not by the desire to beat others.", author: "Ayn Rand" },
    { quote: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
    { quote: "Don’t judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
    { quote: "An unexamined life is not worth living.", author: "Socrates" },
    { quote: "Do what you love, and you’ll never work another day in your life.", author: "Marc Anthony" },
    { quote: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous" },
    { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    { quote: "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed.", author: "Tony Robbins" },
    { quote: "The real opportunity for success lies within the person and not in the job.", author: "Zig Ziglar" },
    { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
    { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    { quote: "Don’t let the fear of losing be greater than the excitement of winning.", author: "Robert Kiyosaki" },
    { quote: "Stop chasing the money and start chasing the passion.", author: "Tony Hsieh" },
    { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    { quote: "Try not to become a man of success, but rather become a man of value.", author: "Albert Einstein" },
    { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    { quote: "Don’t cry because it’s over, smile because it happened.", author: "Dr. Seuss" },
    { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { quote: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { quote: "The secret to getting ahead is getting started.", author: "Mark Twain" },
    { quote: "Happiness lies in the joy of achievement and the thrill of creative effort.", author: "Franklin D. Roosevelt" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { quote: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { quote: "The best way out is always through.", author: "Robert Frost" },
    { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { quote: "Nothing will work unless you do.", author: "Maya Angelou" },
    { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
    { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { quote: "Opportunities are usually disguised as hard work, so most people don’t recognize them.", author: "Ann Landers" },
    { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    { quote: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { quote: "Nothing is impossible, the word itself says ‘I’m possible’!", author: "Audrey Hepburn" },
    { quote: "If you want to achieve greatness, stop asking for permission.", author: "Anonymous" },
    { quote: "Dream as if you’ll live forever. Live as if you’ll die today.", author: "James Dean" },
    { quote: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown, Jr." }
  ];